# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base_types.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62\x61se_types.proto\"+\n\x0c\x42\x61seResponse\x12\r\n\x05state\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\"\x84\x01\n\x0b\x42otResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08tg_token\x18\x02 \x01(\t\x12\x14\n\x0cgoogle_token\x18\x03 \x01(\t\x12\r\n\x05owner\x18\x04 \x01(\x05\x12\x15\n\rbot_survey_id\x18\x05 \x01(\x05\x12\r\n\x05state\x18\x06 \x01(\t\x12\x0c\n\x04\x63ode\x18\x07 \x01(\x05\"\x95\x01\n\x06Module\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x15\n\rquestion_type\x18\x02 \x01(\t\x12\x13\n\x0b\x61nswer_type\x18\x03 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t\x12\x18\n\x07\x62uttons\x18\x05 \x03(\x0b\x32\x07.Button\x12\x18\n\x10next_question_id\x18\x06 \x01(\x05\x12\n\n\x02id\x18\x07 \x01(\x05\"0\n\x06\x41nswer\x12\x11\n\tmodule_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x61nswer_text\x18\x02 \x01(\t\"j\n\x07Journal\x12&\n\x07modules\x18\x01 \x03(\x0b\x32\x15.Journal.ModulesEntry\x1a\x37\n\x0cModulesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x16\n\x05value\x18\x02 \x01(\x0b\x32\x07.Module:\x02\x38\x01\";\n\x04User\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontact\x18\x03 \x01(\t\"L\n\x06\x42utton\x12\x13\n\x0bquestion_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x61nswer_text\x18\x02 \x01(\t\x12\x18\n\x10next_question_id\x18\x03 \x01(\x05\"`\n\x0cUserResponse\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontact\x18\x03 \x01(\t\x12\r\n\x05state\x18\x04 \x01(\t\x12\x0c\n\x04\x63ode\x18\x05 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'base_types_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _JOURNAL_MODULESENTRY._options = None
  _JOURNAL_MODULESENTRY._serialized_options = b'8\001'
  _BASERESPONSE._serialized_start=20
  _BASERESPONSE._serialized_end=63
  _BOTRESPONSE._serialized_start=66
  _BOTRESPONSE._serialized_end=198
  _MODULE._serialized_start=201
  _MODULE._serialized_end=350
  _ANSWER._serialized_start=352
  _ANSWER._serialized_end=400
  _JOURNAL._serialized_start=402
  _JOURNAL._serialized_end=508
  _JOURNAL_MODULESENTRY._serialized_start=453
  _JOURNAL_MODULESENTRY._serialized_end=508
  _USER._serialized_start=510
  _USER._serialized_end=569
  _BUTTON._serialized_start=571
  _BUTTON._serialized_end=647
  _USERRESPONSE._serialized_start=649
  _USERRESPONSE._serialized_end=745
# @@protoc_insertion_point(module_scope)
