# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: web_api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import my_types.base_types_pb2 as base__types__pb2
import clients.bot.bot_pb2 as bot__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rweb_api.proto\x1a\x10\x62\x61se_types.proto\x1a\tbot.proto2A\n\nDataSender\x12\x33\n\nCreate_Bot\x12\x11.CreateBotRequest\x1a\x12.CreateBotResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'web_api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_DATASENDER']._serialized_start=46
  _globals['_DATASENDER']._serialized_end=111
# @@protoc_insertion_point(module_scope)
