# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import clients.bot.bot_pb2 as bot__pb2


class DataSenderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create_Bot = channel.unary_unary(
                '/DataSender/Create_Bot',
                request_serializer=bot__pb2.CreateBotRequest.SerializeToString,
                response_deserializer=bot__pb2.CreateBotResponse.FromString,
                )


class DataSenderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create_Bot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataSenderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create_Bot': grpc.unary_unary_rpc_method_handler(
                    servicer.Create_Bot,
                    request_deserializer=bot__pb2.CreateBotRequest.FromString,
                    response_serializer=bot__pb2.CreateBotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DataSender', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataSender(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create_Bot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DataSender/Create_Bot',
            bot__pb2.CreateBotRequest.SerializeToString,
            bot__pb2.CreateBotResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
