# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import my_types.base_types_pb2 as base__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x1a\x10\x62\x61se_types.proto\")\n\x16GetUserBotsListRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"R\n\x17GetUserBotsListResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\r\n\x05state\x18\x02 \x01(\t\x12\x1a\n\x04\x62ots\x18\x03 \x03(\x0b\x32\x0c.BotResponse2\xa1\x01\n\nUserWorker\x12\"\n\nRegNewUser\x12\x05.User\x1a\r.BaseResponse\x12)\n\x07GetUser\x12\x0f.GetUserRequest\x1a\r.UserResponse\x12\x44\n\x0fGetUserBotsList\x12\x17.GetUserBotsListRequest\x1a\x18.GetUserBotsListResponseB\x19\xaa\x02\x16\x44\x61taBaseService.Protosb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\026DataBaseService.Protos'
  _GETUSERBOTSLISTREQUEST._serialized_start=32
  _GETUSERBOTSLISTREQUEST._serialized_end=73
  _GETUSERREQUEST._serialized_start=75
  _GETUSERREQUEST._serialized_end=108
  _GETUSERBOTSLISTRESPONSE._serialized_start=110
  _GETUSERBOTSLISTRESPONSE._serialized_end=192
  _USERWORKER._serialized_start=195
  _USERWORKER._serialized_end=356
# @@protoc_insertion_point(module_scope)
