# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import base_types_pb2 as base__types__pb2
import user_pb2 as user__pb2


class UserWorkerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegNewUser = channel.unary_unary(
                '/UserWorker/RegNewUser',
                request_serializer=base__types__pb2.User.SerializeToString,
                response_deserializer=base__types__pb2.BaseResponse.FromString,
                )
        self.GetUser = channel.unary_unary(
                '/UserWorker/GetUser',
                request_serializer=user__pb2.GetUserRequest.SerializeToString,
                response_deserializer=base__types__pb2.UserResponse.FromString,
                )
        self.GetUserBotsList = channel.unary_unary(
                '/UserWorker/GetUserBotsList',
                request_serializer=user__pb2.GetUserBotsListRequest.SerializeToString,
                response_deserializer=user__pb2.GetUserBotsListResponse.FromString,
                )


class UserWorkerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegNewUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserBotsList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegNewUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RegNewUser,
                    request_deserializer=base__types__pb2.User.FromString,
                    response_serializer=base__types__pb2.BaseResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=user__pb2.GetUserRequest.FromString,
                    response_serializer=base__types__pb2.UserResponse.SerializeToString,
            ),
            'GetUserBotsList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserBotsList,
                    request_deserializer=user__pb2.GetUserBotsListRequest.FromString,
                    response_serializer=user__pb2.GetUserBotsListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UserWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserWorker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegNewUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserWorker/RegNewUser',
            base__types__pb2.User.SerializeToString,
            base__types__pb2.BaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserWorker/GetUser',
            user__pb2.GetUserRequest.SerializeToString,
            base__types__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserBotsList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserWorker/GetUserBotsList',
            user__pb2.GetUserBotsListRequest.SerializeToString,
            user__pb2.GetUserBotsListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
