# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import base_types_pb2 as base__types__pb2
import bot_pb2 as bot__pb2


class BotGetterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBotById = channel.unary_unary(
                '/BotGetter/GetBotById',
                request_serializer=bot__pb2.GetBotRequest.SerializeToString,
                response_deserializer=base__types__pb2.Bot.FromString,
                )


class BotGetterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBotById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BotGetterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBotById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBotById,
                    request_deserializer=bot__pb2.GetBotRequest.FromString,
                    response_serializer=base__types__pb2.Bot.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BotGetter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BotGetter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBotById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BotGetter/GetBotById',
            bot__pb2.GetBotRequest.SerializeToString,
            base__types__pb2.Bot.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
