# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bot.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base_types_pb2 as base__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tbot.proto\x1a\x10\x62\x61se_types.proto\"\x1f\n\rGetBotRequest\x12\x0e\n\x06\x62ot_id\x18\x01 \x01(\x05\x32/\n\tBotGetter\x12\"\n\nGetBotById\x12\x0e.GetBotRequest\x1a\x04.Botb\x06proto3')



_GETBOTREQUEST = DESCRIPTOR.message_types_by_name['GetBotRequest']
GetBotRequest = _reflection.GeneratedProtocolMessageType('GetBotRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETBOTREQUEST,
  '__module__' : 'bot_pb2'
  # @@protoc_insertion_point(class_scope:GetBotRequest)
  })
_sym_db.RegisterMessage(GetBotRequest)

_BOTGETTER = DESCRIPTOR.services_by_name['BotGetter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETBOTREQUEST._serialized_start=31
  _GETBOTREQUEST._serialized_end=62
  _BOTGETTER._serialized_start=64
  _BOTGETTER._serialized_end=111
# @@protoc_insertion_point(module_scope)
